### ISSUE TITLE
Private API key in public repository

### ISSUE THREAD

**Issue by jjaeggli** [aerickson/prusaslicer_settings_for_lulzbot#1]
While unlikely to ever be a problem, you might consider invalidating and removing this API key:

https://github.com/aerickson/prusaslicer_settings_for_lulzbot/blob/f33170fe7b90a6ab6596446db52bc9c3389f8f6d/mini1/standard_extruder/config.ini#L152

**Comment by aerickson** [comment]
Thanks. I am aware, but decided it was low risk as I don't expose my OctoPrint anywhere. 

TODO: Write a pre-commit hook that sanitizes this.

**Comment by aerickson** [comment]
pre-commit hook written and landed.
